title: "Transports du Futur"
description: "Exploration des mobilites, de l'innovation et des transports"
baseurl: "/blog"
url: "https://gabrielplassat.github.io"

author:
  name: "Gabriel Plassat"

theme: minima
permalink: /:year/:month/:day/:title/
timezone: Europe/Paris
lang: fr
encoding: utf-8

paginate: 20
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

twitter:
  username: gabrielplassat

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor